### ISSUE TITLE
Can not find gazebo_naoqi_control

### ISSUE THREAD

**Issue by Ruqaiya97** [costashatz/nao_gazebo#11]
I am new to ROS and linux and am unable to understand how to execute the following instruction.
"You need to have either environmental variable AL_SIM_DIR or CMake option NAOqi_SIM_DIR pointing to the C++ NAOqi Simulator SDK path."
Your prompt reply will be appreciated.

**Comment by costashatz** [comment]
You need to have the NAOqi Simulator SDK: http://doc.aldebaran.com/1-14/ref/simulator_sdk.html

Once you have this, then do `export AL_SIM_DIR=/path/to/simulator/sdk-lib` to execute this instruction.. You need to do this every time you open a new bash/terminal. If you want to have it always, then put this line into your `.bashrc`.

**Comment by Ruqaiya97** [comment]
Thank you for replying. Sir, I keep getting this error. If you can tell the steps you followed before the roslaunch command, it would be very helpful.
[nao_gazebo.launch] is neither a launch file in package [gazebo_naoqi_control] nor is [gazebo_naoqi_control] a launch file name
The traceback for the exception was written to the log file

**Comment by costashatz** [comment]
> Sir, I keep getting this error. If you can tell the steps you followed before the roslaunch command, it would be very helpful.
> [nao_gazebo.launch] is neither a launch file in package [gazebo_naoqi_control] nor is [gazebo_naoqi_control] a launch file name
> The traceback for the exception was written to the log file

Did you `catkin_make`?

**Comment by Ruqaiya97** [comment]
I realized my mistake, that problem has been solved but now I'm getting a new problem. when I roslaunch the nao_gazebo.launch it opens Gazebo but crashes immediately with this error.
Error [Plugin.hh:149] Failed to load plugin libgazebo_naoqi_control.so: libgazebo_naoqi_control.so: cannot open shared object file: No such file or directory
Segmentation fault (core dumped)
