### ISSUE TITLE
error : fail to load gazebo_naoqi_control plugin

### ISSUE THREAD

**Issue by Yanzqing** [costashatz/nao_gazebo#2]
Error [Model.cc:779] Exception occured in the Load function of plugin with name[gazebo_naoqi_control] and filename[libgazebo_naoqi_control.so]. This plugin will not run.
I am using Indigo

**Comment by costashatz** [comment]
Can you provide more detailed output of the program? What command are you running? Which version of NAOqi Simulator SDK are you using? Have you set the environmental variables properly?

**Comment by Yanzqing** [comment]
My NAOqi Simulator SDK is simulator-sdk-2.1.2.17-linux64, I have set the  environmental variables  AL_SIM_DIR and AL_DIR pointing to the C++ NAOqi Simulator SDK path and C++ NAOqi SDK path.
    In my own workspace, there are three packages(control_toolbox-indigo-devel, nao_gazebo-master, realtime_tools-indigo-devel) in the src folder, and they were compiled successfully
    My gazebo version is 2.2.5, and i am using Indigo 
    Then I run the the command 
    $ roslaunch gazebo_naoqi_control nao_gazebo.launch
  it comes up with the error 
 Error [Model.cc:779] Exception occured in the Load function of plugin with name[gazebo_naoqi_control] and filename[libgazebo_naoqi_control.so]. This plugin will not run.

 Thank you for your reply!

**Comment by costashatz** [comment]
I cannot reproduce the error (I created a workspace as you mentioned).. Do you have nao_meshes in your workspace? It seems that it is needed!

**Comment by jlanca** [comment]
I don't know if this could explain Yanzqing's issue, but it seems the code that uses the simulator-sdk path could be more robust:
`new Sim::Model(naoqi_sim_path_+"share/alrobotmodel/models/"+naoqi_model_type_+".xml");`
Here if NAOQI_SIM_SDK=/path/to/simulator-sdk doesn't have a trailing "/", appending the strings in the above line don't produce the correct path.
Using something like boost::filesystem::path instead of string could make this more robust.

**Comment by costashatz** [comment]
You are right! You should find many little flaws like this in the code! I will fix it asap and please @Yanzqing reply if it fixes your problem.

**Comment by costashatz** [comment]
@Yanzqing @jlanca I have fixed this possible issue. Please @Yanzqing report if it this fixes your problem.

**Comment by Yanzqing** [comment]
It fix my problem successfully, Thank you for your help!

**Comment by costashatz** [comment]
Nice! Big thanks to @jlanca !

**Comment by zhaozj89** [comment]
Hi, all I meet the same problem, but @jlanca 's solution does not work for me. Can someone help me with it? Thanks!

**Comment by costashatz** [comment]
Hello,

Did you find what's wrong with it?


On Sat, Jul 2, 2016 at 2:50 PM Zhenjie Zhao <notifications@github.com>
wrote:

> Hi, all I meet the same problem, but @jlanca <https://github.com/jlanca>
> 's solution does not work for me. Can someone help me with it? Thanks!
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/costashatz/nao_gazebo/issues/2#issuecomment-230100268>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABOXUnMnFFvJcOIXH9MdD2vDALRMDNaYks5qRl6ogaJpZM4ECt8w>
> .
>
-- 
Konstantinos Chatzilygeroudis
PhD Candidate
Team Larsen
INRIA Nancy Grand-Est
Room C121
e-mail: konstantinos.chatzilygeroudis@inria.fr
web: http://costashatz.github.io/

**Comment by zhaozj89** [comment]
Thank you. I tried your method in #4 , it is OK now. So sorry that I did not notice all the issues, and I have deleted my previous comment. Sorry. Thanks again.
