### ISSUE TITLE
Package setup step!

### ISSUE THREAD

**Issue by pouryashahverdi** [costashatz/nao_gazebo#4]
Hi dear developers
I'm new in ros!
How can I implement follow step of making nao_gazebo package?

-----------------------------------------------------------------------------------------------
Building/Compiling
------------------
You need to have either environmental variable AL_SIM_DIR or CMake option NAOqi_SIM_DIR pointing to the C++ NAOqi Simulator SDK path.

Also, you need to have either environmental variable AL_DIR or CMake option NAOqi_DIR pointing to the C++ NAOqi SDK path.

Check cmake/FindNAOqiSIM.cmake for more details.
----------------------------------------------------------------------------------------------

King Regards
Pourya

**Comment by costashatz** [comment]
Hello @pouryashahverdi! Welcome to the ROS community.

There are 2 ways of implementing this step (I suggest the first one):

### Using environmental variables

You can check this guide for details on handling environmental variables in Ubuntu: https://help.ubuntu.com/community/EnvironmentVariables

But you only have to do the following:

in you `.bashrc` file:

```bash
export AL_SIM_DIR=path_to_simulator_sdk
export AL_DIR=path_to_naoqi_sdk
```

### Using CMake

You only have to do the following:

In the CMakeLists.txt (of gazebo_naoqi_control):

Replace these two lines:
```cmake
# Tell Program where to find NAOqi/NAOqiSIM bin
add_definitions(-DNAOQI_SDK="$ENV{AL_DIR}")
add_definitions(-DNAOQI_SIM_SDK="$ENV{AL_SIM_DIR}")
```

with:

```cmake
# Tell Program where to find NAOqi/NAOqiSIM bin
add_definitions(-DNAOQI_SDK="path_to_naoqi_sdk")
add_definitions(-DNAOQI_SIM_SDK="path_to_sim_sdk")
```

**Comment by pouryashahverdi** [comment]
Thanks a lot :)

**Comment by costashatz** [comment]
@pouryashahverdi did it work?

**Comment by sahmad98** [comment]
It is not working for me.

Error is 

In file included from /home/saleem/catkin_ws/src/nao_gazebo/gazebo_naoqi_control/src/gazebo_naoqi_control_plugin.cpp:24:0:
/home/saleem/catkin_ws/src/nao_gazebo/gazebo_naoqi_control/include/gazebo_naoqi_control/gazebo_naoqi_control_plugin.h:45:31: fatal error: alnaosim/alnaosim.h: No such file or directory
 #include <alnaosim/alnaosim.h>
                               ^
compilation terminated.
make[2]: *** [nao_gazebo/gazebo_naoqi_control/CMakeFiles/gazebo_naoqi_control.dir/src/gazebo_naoqi_control_plugin.cpp.o] Error 1
make[1]: *** [nao_gazebo/gazebo_naoqi_control/CMakeFiles/gazebo_naoqi_control.dir/all] Error 2
make: *** [all] Error 2
Invoking "make -j4 -l4" failed

**Comment by costashatz** [comment]
See #5 . Closing this..
