### ISSUE TITLE
error in compilation

### ISSUE THREAD

**Issue by sahmad98** [costashatz/nao_gazebo#5]
Compilation Failing due to error,
I have added AL_DIR and AL_SIM_DIR env variables.

Error is

In file included from /home/saleem/catkin_ws/src/nao_gazebo/gazebo_naoqi_control/src/gazebo_naoqi_control_plugin.cpp:24:0:
/home/saleem/catkin_ws/src/nao_gazebo/gazebo_naoqi_control/include/gazebo_naoqi_control/gazebo_naoqi_control_plugin.h:45:31: fatal error: alnaosim/alnaosim.h: No such file or directory
#include 
^
compilation terminated.
make[2]: *** [nao_gazebo/gazebo_naoqi_control/CMakeFiles/gazebo_naoqi_control.dir/src/gazebo_naoqi_control_plugin.cpp.o] Error 1
make[1]: *** [nao_gazebo/gazebo_naoqi_control/CMakeFiles/gazebo_naoqi_control.dir/all] Error 2
make: *** [all] Error 2
Invoking "make -j4 -l4" failed

**Comment by costashatz** [comment]
@sahmad98 what version of NaoQi and NaoQiSim do you have?

**Comment by sahmad98** [comment]
naoqi - 2.1.14
naoqisim - 2.1.2

**Comment by jokla** [comment]
I am not sure... Did you try to use the same version of the naoqi SDK and the naoqisim (2.1.2)?

**Comment by costashatz** [comment]
> my paths are
> AL_DIR -- ~/naoqi/naoqi-sdk-2.1.4.13-linux64
> AL_SIM_DIR -- ~/naoqi/simulator-sdk-2.1.2.17-linux64

One quick thing to try is to put full paths: e.g. `/home/user/naoqi/....`

I will have more time later this week to try on my own setup..

**Comment by sahmad98** [comment]
I have tried pulling the full paths also. I resolved the issue by hard coding the full header path in the header files, but fearing for any issue later time. Motion and Proxy commands are working for me. 

Thanks @costashatz and @jokla  for your support.
